version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: meals_finder_pg_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
